import './globals.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import Providers from './providers';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface IRootLayoutProps {
  children: Readonly<ReactNode>;
}

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <Providers>
      <html lang="en">
      <body>
      {children}
      </body>
      </html>
    </Providers>
  );
}
